name: Test Audit
on: [push]

jobs:
  audit:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Run audit on https://www.wanted.co.kr/events
      uses: ./
      with:
        url: 'https://www.wanted.co.kr/events'
    - uses: actions/upload-artifact@master
      with:
        name: report
        path: './report'